# Generated by Django 4.2.7 on 2024-01-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'test name'},
        ),
    ]
